In [1]:
import torch
import torch.nn as nn

In [17]:
x = torch.randn(2, 3, requires_grad=True)
x

tensor([[-1.5632,  0.1844, -0.4268],
        [ 0.7113, -0.5674,  0.3260]], requires_grad=True)

In [18]:
y = torch.fft.fft(x)
y

tensor([[-1.8056+0.0000j, -1.4420-0.5294j, -1.4420+0.5294j],
        [ 0.4699+0.0000j,  0.8320+0.7737j,  0.8320-0.7737j]],
       grad_fn=<FftR2CBackward0>)

In [ ]:
# grad can be implicitly created only for scalar outputs
# therefore, y.backward() is impossible.
loss = (y.abs()**2).sum()
loss

tensor(10.7816, grad_fn=<SumBackward0>)

In [23]:
loss.backward()
x.grad

tensor([[-9.3790,  1.1066, -2.5611],
        [ 4.2680, -3.4042,  1.9559]])

In [25]:
torch.tensor([[1]]).size()

torch.Size([1, 1])

In [ ]:
torch.randn((3, 3)).masked_fill(torch.tril(torch.ones(3, 3)) == 0, float("-inf"))

tensor([[-0.1449,    -inf,    -inf],
        [-0.2637, -1.4171,    -inf],
        [-0.3933, -0.4145, -0.7251]])